-- Reusable, provider-agnostic Product Media Library.
create table catalog.media_assets(
 id uuid primary key default gen_random_uuid(),provider_key text not null,provider_locator text not null,public_url text not null,
 mime_type text,width_pixels integer,height_pixels integer,licensing_confirmed_at timestamptz not null,uploaded_by text not null,
 created_at timestamptz not null default statement_timestamp(),updated_at timestamptz not null default statement_timestamp(),
 constraint media_assets_provider_format check(provider_key~'^[a-z0-9]+(?:-[a-z0-9]+)*$'),constraint media_assets_locator_present check(btrim(provider_locator)<>''),
 constraint media_assets_url_present check(btrim(public_url)<>''),constraint media_assets_mime_approved check(mime_type is null or mime_type in('image/jpeg','image/png','image/webp')),
 constraint media_assets_dimensions_valid check((width_pixels is null and height_pixels is null)or(width_pixels>=800 and height_pixels>=800)),unique(provider_key,provider_locator)
);
alter table catalog.product_media add column asset_id uuid references catalog.media_assets(id) on delete restrict;
insert into catalog.media_assets(provider_key,provider_locator,public_url,mime_type,width_pixels,height_pixels,licensing_confirmed_at,uploaded_by,created_at,updated_at)
select case when object_path is null then 'legacy-url' else 'supabase-storage' end,coalesce(object_path,storage_path),storage_path,mime_type,width_pixels,height_pixels,coalesce(licensing_confirmed_at,created_at),coalesce(uploaded_by,'legacy-import'),created_at,updated_at from catalog.product_media on conflict(provider_key,provider_locator)do nothing;
update catalog.product_media m set asset_id=a.id from catalog.media_assets a where a.provider_locator=coalesce(m.object_path,m.storage_path) and a.provider_key=case when m.object_path is null then 'legacy-url' else 'supabase-storage' end;
drop index if exists catalog.product_media_object_path_unique;
alter table catalog.product_media drop constraint if exists product_media_path_unique;
alter table catalog.media_assets enable row level security;revoke all on catalog.media_assets from public,anon,authenticated;grant all on catalog.media_assets to service_role;

create or replace function public.admin_media_library()returns jsonb language sql stable security definer set search_path='' as $$select case when public.is_reyon_admin()then coalesce(jsonb_agg(jsonb_build_object('id',id,'provider',provider_key,'locator',provider_locator,'url',public_url,'mimeType',mime_type,'width',width_pixels,'height',height_pixels,'licensingConfirmedAt',licensing_confirmed_at,'createdAt',created_at)order by created_at desc),'[]'::jsonb)else null end from catalog.media_assets$$;
create or replace function public.admin_create_media_asset(p_provider_key text,p_provider_locator text,p_url text,p_mime_type text,p_width integer,p_height integer)returns uuid language plpgsql security definer set search_path='' as $$declare new_id uuid;begin if not public.is_reyon_admin()then raise exception'Administrator access required.';end if;insert into catalog.media_assets(provider_key,provider_locator,public_url,mime_type,width_pixels,height_pixels,licensing_confirmed_at,uploaded_by)values(p_provider_key,btrim(p_provider_locator),btrim(p_url),p_mime_type,p_width,p_height,statement_timestamp(),coalesce(auth.jwt()->>'email',auth.uid()::text))returning id into new_id;return new_id;end$$;
create or replace function public.admin_attach_media_asset(p_product_id uuid,p_asset_id uuid,p_alt_text text)returns uuid language plpgsql security definer set search_path='' as $$declare new_id uuid;count_images integer;a catalog.media_assets%rowtype;begin if not public.is_reyon_admin()then raise exception'Administrator access required.';end if;select count(*)into count_images from catalog.product_media where product_id=p_product_id;if count_images>=12 then raise exception'A product can have no more than 12 images.';end if;select*into a from catalog.media_assets where id=p_asset_id;if a.id is null then raise exception'Media asset not found.';end if;insert into catalog.product_media(product_id,asset_id,storage_path,object_path,alt_text,display_order,is_primary,mime_type,width_pixels,height_pixels,licensing_confirmed_at,uploaded_by)values(p_product_id,a.id,a.public_url,case when a.provider_key='supabase-storage'then a.provider_locator end,btrim(p_alt_text),count_images,count_images=0,a.mime_type,a.width_pixels,a.height_pixels,a.licensing_confirmed_at,a.uploaded_by)returning id into new_id;perform catalog.normalize_product_media(p_product_id);return new_id;end$$;
create or replace function public.admin_create_product_with_asset(p_name text,p_slug text,p_brand_id uuid,p_category_id uuid,p_variant_type text,p_variant_label text,p_sku text,p_barcode text,p_purchase_price numeric,p_selling_price numeric,p_compare_at_price numeric,p_discount_price numeric,p_asset_id uuid,p_image_alt text,p_country_code text,p_product_code text,p_publish boolean default true)returns uuid language plpgsql security definer set search_path='' as $$declare new_product_id uuid;a catalog.media_assets%rowtype;begin select*into a from catalog.media_assets where id=p_asset_id;if a.id is null then raise exception'Media asset is required.';end if;new_product_id:=public.admin_create_product(p_name,p_slug,p_brand_id,p_category_id,p_variant_type,p_variant_label,p_sku,p_barcode,p_purchase_price,p_selling_price,p_compare_at_price,p_discount_price,a.public_url,p_image_alt,p_country_code,p_product_code,p_publish);update catalog.product_media set asset_id=a.id,object_path=case when a.provider_key='supabase-storage'then a.provider_locator end,mime_type=a.mime_type,width_pixels=a.width_pixels,height_pixels=a.height_pixels,licensing_confirmed_at=a.licensing_confirmed_at,uploaded_by=a.uploaded_by where catalog.product_media.product_id=new_product_id;return new_product_id;end$$;
revoke all on function public.admin_media_library()from public,anon;revoke all on function public.admin_create_media_asset(text,text,text,text,integer,integer)from public,anon;revoke all on function public.admin_attach_media_asset(uuid,uuid,text)from public,anon;revoke all on function public.admin_create_product_with_asset(text,text,uuid,uuid,text,text,text,text,numeric,numeric,numeric,numeric,uuid,text,text,text,boolean)from public,anon;
grant execute on function public.admin_media_library()to authenticated;grant execute on function public.admin_create_media_asset(text,text,text,text,integer,integer)to authenticated;grant execute on function public.admin_attach_media_asset(uuid,uuid,text)to authenticated;grant execute on function public.admin_create_product_with_asset(text,text,uuid,uuid,text,text,text,text,numeric,numeric,numeric,numeric,uuid,text,text,text,boolean)to authenticated;
create or replace function public.admin_replace_product_media_asset(p_media_id uuid,p_asset_id uuid,p_alt_text text)returns void language plpgsql security definer set search_path='' as $$declare a catalog.media_assets%rowtype;begin if not public.is_reyon_admin()then raise exception'Administrator access required.';end if;select*into a from catalog.media_assets where id=p_asset_id;if a.id is null then raise exception'Media asset not found.';end if;update catalog.product_media set asset_id=a.id,storage_path=a.public_url,object_path=case when a.provider_key='supabase-storage'then a.provider_locator end,alt_text=btrim(p_alt_text),mime_type=a.mime_type,width_pixels=a.width_pixels,height_pixels=a.height_pixels,licensing_confirmed_at=a.licensing_confirmed_at,uploaded_by=a.uploaded_by where id=p_media_id;if not found then raise exception'Product image not found.';end if;end$$;revoke all on function public.admin_replace_product_media_asset(uuid,uuid,text)from public,anon;grant execute on function public.admin_replace_product_media_asset(uuid,uuid,text)to authenticated;
comment on table catalog.media_assets is 'Reusable provider-agnostic physical media assets; product_media remains the ordered product association.';
create or replace function public.admin_media_object_is_referenced(p_object_path text)returns boolean language sql stable security definer set search_path='' as $$select public.is_reyon_admin()and exists(select 1 from catalog.media_assets where provider_key='supabase-storage'and provider_locator=p_object_path)$$;
