-- REYON Business OS: provider-neutral, failure-safe notification outbox.
create schema if not exists notifications;revoke all on schema notifications from public,anon,authenticated;grant usage on schema notifications to service_role;
create table notifications.outbox(id uuid primary key default gen_random_uuid(),event_key text not null,audience_key text not null check(audience_key in('customer','admin')),order_id uuid references sales.orders(id)on delete restrict,payload jsonb not null default'{}',status_key text not null default'pending'check(status_key in('pending','processing','sent','failed')),created_at timestamptz not null default statement_timestamp(),constraint outbox_event_format check(event_key~'^[a-z0-9]+(?:-[a-z0-9]+)*$'));
create table notifications.delivery_attempts(id uuid primary key default gen_random_uuid(),outbox_id uuid not null references notifications.outbox(id)on delete restrict,provider_key text not null,attempted_at timestamptz not null default statement_timestamp(),outcome_key text not null check(outcome_key in('sent','failed')),provider_reference text,error_summary text);
create trigger outbox_prevent_delete before delete on notifications.outbox for each row execute function sales.prevent_transition_mutation();create trigger attempts_prevent_mutation before update or delete on notifications.delivery_attempts for each row execute function sales.prevent_transition_mutation();
alter table notifications.outbox enable row level security;alter table notifications.delivery_attempts enable row level security;revoke all on all tables in schema notifications from public,anon,authenticated;grant all on all tables in schema notifications to service_role;
create or replace function notifications.enqueue_order_transition()returns trigger language plpgsql security definer set search_path=''as $$begin insert into notifications.outbox(event_key,audience_key,order_id,payload)values('order-'||new.to_state_key,'customer',new.order_id,jsonb_build_object('transitionId',new.id)),('order-'||new.to_state_key,'admin',new.order_id,jsonb_build_object('transitionId',new.id));return new;end$$;
create trigger order_transition_notification after insert on sales.order_transitions for each row execute function notifications.enqueue_order_transition();
create or replace function notifications.enqueue_payment_event()returns trigger language plpgsql security definer set search_path=''as $$begin insert into notifications.outbox(event_key,audience_key,order_id,payload)values('payment-'||new.new_state_key,'customer',new.order_id,jsonb_build_object('paymentEventId',new.id)),('payment-'||new.new_state_key,'admin',new.order_id,jsonb_build_object('paymentEventId',new.id));return new;end$$;
create trigger payment_event_notification after insert on payments.manual_verification_events for each row execute function notifications.enqueue_payment_event();
create or replace function public.admin_notification_outbox()returns jsonb language sql stable security definer set search_path=''as $$select case when public.is_reyon_admin()then coalesce(jsonb_agg(jsonb_build_object('id',n.id,'event',n.event_key,'audience',n.audience_key,'orderNumber',o.external_reference,'status',n.status_key,'createdAt',n.created_at)order by n.created_at desc),'[]'::jsonb)else null end from notifications.outbox n left join sales.orders o on o.id=n.order_id$$;
revoke all on function public.admin_notification_outbox()from public,anon;grant execute on function public.admin_notification_outbox()to authenticated;
