-- Sprint 15 configurable manual payment selection.
create table payments.checkout_methods(id uuid primary key default gen_random_uuid(),method_key text not null unique,name text not null,method_kind text not null,display_order integer not null,is_visible boolean not null default true,is_selectable boolean not null default false,instructions text,account_reference text,updated_at timestamptz not null default statement_timestamp(),constraint method_kind_allowed check(method_kind in('mobile','card','cod')),constraint selectable_mobile_config check(method_kind<>'mobile' or not is_selectable or (instructions is not null and account_reference is not null)),constraint card_not_manual_success check(method_kind<>'card' or not is_selectable));
insert into payments.checkout_methods(method_key,name,method_kind,display_order,is_selectable) values('bkash','bKash','mobile',10,false),('nagad','Nagad','mobile',20,false),('rocket','Rocket','mobile',30,false),('card','Card','card',40,false),('cod','Cash on Delivery','cod',50,true);
create table commerce.checkout_payment_selections(cart_id uuid primary key references commerce.carts(id) on delete cascade,method_id uuid not null references payments.checkout_methods(id) on delete restrict,transaction_reference text,selected_at timestamptz not null default statement_timestamp(),updated_at timestamptz not null default statement_timestamp());
alter table payments.checkout_methods enable row level security;alter table commerce.checkout_payment_selections enable row level security;revoke all on payments.checkout_methods,commerce.checkout_payment_selections from public,anon,authenticated;grant all on payments.checkout_methods,commerce.checkout_payment_selections to service_role;
create or replace function public.checkout_payment_methods() returns table(id uuid,method_key text,name text,method_kind text,is_selectable boolean,instructions text,account_reference text) language sql stable security definer set search_path='' as $$select id,method_key,name,method_kind,is_selectable,instructions,account_reference from payments.checkout_methods where is_visible order by display_order$$;
create or replace function public.checkout_select_payment(p_access_token uuid,p_method_id uuid,p_transaction_reference text default null) returns void language plpgsql security definer set search_path='' as $$declare owned_cart uuid;kind text;selectable boolean;begin select id into owned_cart from commerce.carts where access_token=p_access_token and expires_at>statement_timestamp();if owned_cart is null then raise exception 'Active cart not found.';end if;select method_kind,is_selectable into kind,selectable from payments.checkout_methods where id=p_method_id and is_visible;if not coalesce(selectable,false) then raise exception 'Payment method is not currently selectable.';end if;if kind='mobile' and nullif(btrim(p_transaction_reference),'') is null then raise exception 'Transaction reference is required.';end if;insert into commerce.checkout_payment_selections(cart_id,method_id,transaction_reference)values(owned_cart,p_method_id,nullif(btrim(p_transaction_reference),''))on conflict(cart_id)do update set method_id=excluded.method_id,transaction_reference=excluded.transaction_reference,updated_at=statement_timestamp();end$$;
create or replace function public.admin_payment_methods() returns jsonb language sql stable security definer set search_path='' as $$select case when public.is_reyon_admin() then coalesce(jsonb_agg(jsonb_build_object('id',id,'key',method_key,'name',name,'kind',method_kind,'isVisible',is_visible,'isSelectable',is_selectable,'instructions',instructions,'accountReference',account_reference,'displayOrder',display_order)order by display_order),'[]'::jsonb)else null end from payments.checkout_methods$$;
revoke all on function public.checkout_payment_methods() from public;revoke all on function public.checkout_select_payment(uuid,uuid,text) from public;revoke all on function public.admin_payment_methods() from public,anon;grant execute on function public.checkout_payment_methods() to anon,authenticated;grant execute on function public.checkout_select_payment(uuid,uuid,text) to anon,authenticated;grant execute on function public.admin_payment_methods() to authenticated;
create or replace function public.admin_update_payment_method(p_method_id uuid,p_is_visible boolean,p_is_selectable boolean,p_instructions text,p_account_reference text) returns void language plpgsql security definer set search_path='' as $$declare kind text;begin if not public.is_reyon_admin() then raise exception 'Administrator access required.';end if;select method_kind into kind from payments.checkout_methods where id=p_method_id;if kind='card' and p_is_selectable then raise exception 'Card requires a real gateway.';end if;update payments.checkout_methods set is_visible=p_is_visible,is_selectable=p_is_selectable,instructions=nullif(btrim(p_instructions),''),account_reference=nullif(btrim(p_account_reference),''),updated_at=statement_timestamp() where id=p_method_id;end$$;revoke all on function public.admin_update_payment_method(uuid,boolean,boolean,text,text) from public,anon;grant execute on function public.admin_update_payment_method(uuid,boolean,boolean,text,text) to authenticated;
