-- REYON Business OS: Sprint 14 approved catalog administration rules.
-- Additive only. This migration introduces no product, brand, supplier, price,
-- inventory, user, or customer data and grants no browser-facing access.

alter table catalog.products
  add column product_code text,
  add column status text not null default 'draft',
  add column country_of_origin_code text,
  add constraint products_product_code_format
    check (product_code is null or product_code ~ '^[A-Za-z0-9][A-Za-z0-9._-]*$'),
  add constraint products_product_code_unique unique (product_code),
  add constraint products_status_approved
    check (status in ('draft', 'review', 'approved', 'published', 'hidden', 'archived')),
  add constraint products_country_origin_iso_alpha2
    check (country_of_origin_code is null or country_of_origin_code ~ '^[A-Z]{2}$');

alter table catalog.variants
  add column variant_type text not null,
  add column sku_source text not null default 'admin-provided',
  add constraint variants_type_approved
    check (variant_type in ('size', 'volume', 'color', 'shade', 'weight', 'pack-size')),
  add constraint variants_sku_source_approved
    check (sku_source in ('system-generated', 'admin-provided'));

alter table catalog.product_media
  add constraint product_media_display_order_nonnegative check (display_order >= 0),
  add constraint product_media_product_order_unique unique (product_id, display_order);

create table catalog.product_provenance (
  product_id uuid primary key references catalog.products(id) on delete restrict,
  authentic_product boolean,
  imported_product boolean,
  supplier_id uuid references purchasing.suppliers(id) on delete restrict,
  official_distributor_name text,
  evidence_reference text,
  created_at timestamptz not null default statement_timestamp(),
  updated_at timestamptz not null default statement_timestamp(),
  constraint product_provenance_distributor_present
    check (official_distributor_name is null or btrim(official_distributor_name) <> ''),
  constraint product_provenance_evidence_present
    check (evidence_reference is null or btrim(evidence_reference) <> '')
);

create index product_provenance_supplier_id_idx
  on catalog.product_provenance(supplier_id);

create table catalog.variant_prices (
  id uuid primary key default gen_random_uuid(),
  variant_id uuid not null references catalog.variants(id) on delete restrict,
  price_type text not null,
  currency_code text not null,
  amount numeric(18, 2) not null,
  created_at timestamptz not null default statement_timestamp(),
  updated_at timestamptz not null default statement_timestamp(),
  constraint variant_prices_type_approved
    check (price_type in ('purchase', 'selling', 'compare-at', 'discount')),
  constraint variant_prices_currency_iso_format check (currency_code ~ '^[A-Z]{3}$'),
  constraint variant_prices_amount_nonnegative check (amount >= 0),
  constraint variant_prices_variant_type_unique unique (variant_id, price_type)
);

create index variant_prices_variant_id_idx
  on catalog.variant_prices(variant_id);

create table catalog.product_status_events (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references catalog.products(id) on delete restrict,
  sequence_number bigint generated by default as identity,
  from_status text not null,
  to_status text not null,
  actor_reference text not null,
  reason text,
  occurred_at timestamptz not null default statement_timestamp(),
  constraint product_status_events_from_approved
    check (from_status in ('draft', 'review', 'approved', 'published', 'hidden', 'archived')),
  constraint product_status_events_to_approved
    check (to_status in ('draft', 'review', 'approved', 'published', 'hidden', 'archived')),
  constraint product_status_events_actor_present check (btrim(actor_reference) <> ''),
  constraint product_status_events_reason_present check (reason is null or btrim(reason) <> ''),
  constraint product_status_events_transition_unique unique (product_id, sequence_number)
);

create index product_status_events_product_time_idx
  on catalog.product_status_events(product_id, occurred_at, sequence_number);

create or replace function catalog.prevent_identity_change()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.id <> old.id then
    raise exception 'Catalog internal IDs are immutable.';
  end if;
  return new;
end;
$$;

create or replace function catalog.prepare_variant_sku()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if tg_op = 'INSERT' and (new.sku is null or btrim(new.sku) = '') then
    new.sku := gen_random_uuid()::text;
    new.sku_source := 'system-generated';
  elsif tg_op = 'INSERT' then
    new.sku_source := 'admin-provided';
  elsif new.sku is distinct from old.sku then
    if new.sku is null or btrim(new.sku) = '' then
      new.sku := gen_random_uuid()::text;
      new.sku_source := 'system-generated';
    else
      new.sku_source := 'admin-provided';
    end if;
  end if;
  return new;
end;
$$;

create or replace function catalog.prevent_append_only_change()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  raise exception 'Catalog lifecycle evidence is append-only.';
end;
$$;

create or replace function catalog.transition_product_status(
  p_target_product_id uuid,
  p_expected_status text,
  p_target_status text,
  p_actor_reference text,
  p_transition_reason text default null
)
returns void
language plpgsql
set search_path = ''
as $$
declare
  current_status text;
begin
  if p_actor_reference is null or btrim(p_actor_reference) = '' then
    raise exception 'An actor reference is required.';
  end if;

  select status into current_status
  from catalog.products
  where id = p_target_product_id
  for update;

  if current_status is null then
    raise exception 'Product does not exist.';
  end if;

  if current_status <> p_expected_status then
    raise exception 'Product status changed concurrently.';
  end if;

  if not (
    (current_status = 'draft' and p_target_status = 'review') or
    (current_status = 'review' and p_target_status = 'approved') or
    (current_status = 'approved' and p_target_status = 'published') or
    (current_status = 'published' and p_target_status = 'hidden') or
    (current_status = 'hidden' and p_target_status = 'archived')
  ) then
    raise exception 'The requested catalog lifecycle transition is not approved.';
  end if;

  if p_target_status = 'published' then
    if not exists (
      select 1 from catalog.product_categories
      where product_id = p_target_product_id and is_primary
    ) then
      raise exception 'Publication requires one primary category.';
    end if;
    if not exists (
      select 1 from catalog.product_media where product_id = p_target_product_id
    ) then
      raise exception 'Publication requires at least one image.';
    end if;
    if not exists (
      select 1 from catalog.variants where product_id = p_target_product_id
    ) then
      raise exception 'Publication requires at least one sellable variant.';
    end if;
  end if;

  update catalog.products
  set status = p_target_status
  where id = p_target_product_id;

  insert into catalog.product_status_events (
    product_id,
    from_status,
    to_status,
    actor_reference,
    reason
  ) values (
    p_target_product_id,
    current_status,
    p_target_status,
    p_actor_reference,
    p_transition_reason
  );
end;
$$;

revoke all on function catalog.prevent_identity_change() from public, anon, authenticated;
revoke all on function catalog.prepare_variant_sku() from public, anon, authenticated;
revoke all on function catalog.prevent_append_only_change() from public, anon, authenticated;
revoke all on function catalog.transition_product_status(uuid, text, text, text, text) from public, anon, authenticated;
grant execute on function catalog.transition_product_status(uuid, text, text, text, text) to service_role;

create trigger products_prevent_identity_change before update on catalog.products
for each row execute function catalog.prevent_identity_change();
create trigger variants_prevent_identity_change before update on catalog.variants
for each row execute function catalog.prevent_identity_change();
create trigger variants_prepare_sku before insert or update of sku on catalog.variants
for each row execute function catalog.prepare_variant_sku();
create trigger product_provenance_set_updated_at before update on catalog.product_provenance
for each row execute function catalog.set_updated_at();
create trigger variant_prices_set_updated_at before update on catalog.variant_prices
for each row execute function catalog.set_updated_at();
create trigger product_status_events_prevent_change before update or delete on catalog.product_status_events
for each row execute function catalog.prevent_append_only_change();

alter table catalog.product_provenance enable row level security;
alter table catalog.variant_prices enable row level security;
alter table catalog.product_status_events enable row level security;

revoke all on catalog.product_provenance from public, anon, authenticated;
revoke all on catalog.variant_prices from public, anon, authenticated;
revoke all on catalog.product_status_events from public, anon, authenticated;
grant all on catalog.product_provenance to service_role;
grant all on catalog.variant_prices to service_role;
grant all on catalog.product_status_events to service_role;
grant usage, select on sequence catalog.product_status_events_sequence_number_seq to service_role;

create view catalog.product_business_references
with (security_invoker = true)
as
select
  id as product_id,
  coalesce(product_code, id::text) as business_reference
from catalog.products;

create view catalog.primary_product_images
with (security_invoker = true)
as
select distinct on (product_id)
  product_id,
  id as media_id,
  storage_path,
  alt_text,
  display_order
from catalog.product_media
order by product_id, display_order, created_at, id;

revoke all on catalog.product_business_references from public, anon, authenticated;
revoke all on catalog.primary_product_images from public, anon, authenticated;
grant select on catalog.product_business_references to service_role;
grant select on catalog.primary_product_images to service_role;

insert into catalog.categories (slug, name, display_order)
values
  ('skin-care', 'Skin Care', 1),
  ('hair-care', 'Hair Care', 2),
  ('makeup', 'Makeup', 3),
  ('perfume', 'Perfume', 4),
  ('baby-care', 'Baby Care', 5),
  ('personal-care', 'Personal Care', 6)
on conflict (slug) do nothing;

comment on column catalog.products.product_code is
  'Optional administrator-entered business code; internal UUID remains immutable identity.';
comment on column catalog.products.country_of_origin_code is
  'Optional ISO 3166-1 alpha-2 country reference prepared for future filtering.';
comment on table catalog.product_provenance is
  'Evidence-ready authenticity, import, supplier, and future distributor facts; does not authorize customer claims.';
comment on table catalog.variant_prices is
  'Approved variant-level price facts; not tax calculation, valuation, promotion, or accounting evidence.';
comment on table catalog.product_status_events is
  'Append-only evidence for the approved catalog lifecycle; actor authorization is a separate pending control.';
